### PR TITLE
Create a Dockerfile

### PR DESCRIPTION
**Pull request by skalee**
This pull request introduces a Dockerfile, which inherits from `Centos:7` image and has GnuPG installed with `install_gpg_all.sh` script.

GnuPG is configured with disabled support for LDAP, Readline, TLS access to keyservers and TOFU. I can reconfigure Dockerfile if needed, it's only a matter of installing four additional packages. Pinentry is configured to use ncurses only.

By default, all components are in their latest versions. Optionally, user may chose 2.2 or 2.1 suite version (as defined in `install_gpg_all.sh` script) instead. Unfortunately, installing from Git is not supported due to outdated version of Automake in CentOS package repository (minimum 1.14 is required whereas only 1.13 is available).

This pull request includes usage example as well. Finally, Dockerfile is tested in Travis CI.

### CODE REVIEW

**Comment by ronaldtse** [comment]
Well, it doesn't exactly solve my problem of installing GnuPG within Docker, because I want to run something "inside" of my Dockerfile. Dockerfiles cannot be built on top of each other -- a Dockerfile cannot be run inside another Dockerfile.

Can't we just move the contents of this Dockerfile into a script that can be run within a Dockerfile?

**Comment by skalee** [comment]
@ronaldtse I guess I can write a dedicated prerequisites installer script which will provide required packages similarly to what `gpg_install_all.sh` previously did. Since it will be a separate program, it does not need to be much portable, and it is okay if it will only work in CentOS. That said, I still does not see much value in a script which will do nothing but `yum install`.

**Comment by skalee** [comment]
Actually @dewyatt's Automake package could be very useful as it solves biggest headaches.

> I noticed this too, I have a ribose-autoamke116 SCL package that I made locally for this that I've been meaning to publish.

_Originally posted by @dewyatt in https://github.com/riboseinc/gpg-build-scripts/pull/24#issuecomment-439865266_

**Comment by dewyatt** [comment]
> Actually @dewyatt's Automake package could be very useful as it solves biggest headaches.

I'll work on getting that published now.

**Comment by dewyatt** [comment]
@skalee The automake116 package is now available in the [ribose rpm repo](https://github.com/riboseinc/yum) if you want to try it (see the [package README](https://github.com/riboseinc/rpm-spec-automake116/blob/master/README.adoc) for usage).

**Pull request merged**
